# Generated by Django 2.2.3 on 2019-07-23 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='hero_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Book'),
        ),
    ]
